from __future__ import annotations
import os
from datetime import datetime
from app.models.scan import ScanRecord, RiskLevel
from app.core.config import settings


RISK_EMOJI = {
    RiskLevel.critical: "🔴",
    RiskLevel.high:     "🟠",
    RiskLevel.medium:   "🟡",
    RiskLevel.low:      "🟢",
}


def generate_report(record: ScanRecord) -> str:
    os.makedirs(settings.reports_dir, exist_ok=True)
    path = os.path.join(settings.reports_dir, f"{record.scan_id}.md")

    findings = record.findings
    summary = record.summary
    shadow = [f for f in findings if f.is_shadow]
    critical = [f for f in findings if f.risk_score >= 80]

    lines: list[str] = [
        "# ReconOps — Attack Surface Assessment Report",
        "",
        f"**Target:** `{record.target}`  ",
        f"**Scan Type:** {record.scan_type.value}  ",
        f"**Scan ID:** `{record.scan_id}`  ",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}  ",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    if summary:
        lines += [
            "| Metric | Value |",
            "|--------|-------|",
            f"| Services Discovered | **{summary.total_services}** |",
            f"| Shadow Services | **{summary.shadow_count}** |",
            f"| Average Risk Score | **{summary.avg_risk}/100** |",
            f"| Max Risk Score | **{summary.max_risk}/100** |",
            f"| Critical | {summary.severity.critical} |",
            f"| High | {summary.severity.high} |",
            f"| Medium | {summary.severity.medium} |",
            f"| Low | {summary.severity.low} |",
            "",
        ]

    lines += ["## Shadow Services Detected", ""]
    if shadow:
        lines += [
            "| Port | Service | Category | Risk | Description |",
            "|------|---------|----------|------|-------------|",
        ]
        for f in sorted(shadow, key=lambda x: x.risk_score, reverse=True):
            icon = RISK_EMOJI.get(f.risk_level, "")
            lines.append(
                f"| {f.port}/{f.protocol} | {f.service} | {f.category.value} "
                f"| {icon} {f.risk_score}/100 | {f.description} |"
            )
    else:
        lines.append("✅ No shadow services detected in this scan.")

    lines += ["", "## All Discovered Services", ""]
    lines += [
        "| Port | Proto | Service | Product | Version | Risk | Shadow |",
        "|------|-------|---------|---------|---------|------|--------|",
    ]
    for f in sorted(findings, key=lambda x: x.risk_score, reverse=True):
        shadow_flag = "⚠️" if f.is_shadow else "—"
        lines.append(
            f"| {f.port} | {f.protocol} | {f.service} | {f.product or '—'} "
            f"| {f.version or '—'} | {f.risk_score}/100 | {shadow_flag} |"
        )

    if critical:
        lines += ["", "## Critical Findings — Immediate Action Required", ""]
        for f in critical:
            lines += [
                f"### Port {f.port} — {f.service}",
                f"**Risk Score:** {f.risk_score}/100  ",
                f"**Category:** {f.category.value}  ",
                f"**Finding:** {f.description}",
                "",
                "**Recommended Action:** Firewall this port from public access. "
                "Verify whether this service is intentionally exposed. "
                "If required, restrict to known IP ranges or VPN.",
                "",
            ]

    lines += [
        "## Methodology",
        "",
        "### 1. Port Scanning (Nmap)",
        "Active TCP port scanning using service version detection (`-sV`). "
        "Discovers listening services with product and version metadata.",
        "",
        "### 2. Asset Enumeration (OWASP Amass)",
        "Passive DNS enumeration to discover subdomains and additional "
        "infrastructure assets associated with domain targets.",
        "",
        "### 3. ML-Assisted Classification (Scikit-learn)",
        "Isolation Forest anomaly detection trained on the discovered port "
        "baseline. Features include port range, privilege level, service "
        "specificity, and known database/admin/legacy port membership. "
        "Composite risk = 60% heuristic + 40% ML anomaly score.",
        "",
        "## Recommendations",
        "",
        "- Implement network segmentation — restrict service exposure by subnet",
        "- Enable host-based firewall (nftables/iptables) with default-deny",
        "- Remove or disable all non-essential listening services",
        "- Enforce TLS 1.2+ on all service communications",
        "- Integrate this scanner into CI/CD pipelines for continuous monitoring",
        "- Review and rotate credentials for all exposed services",
        "",
        "---",
        f"*Generated by ReconOps v1.0 — {datetime.now().strftime('%Y-%m-%d')}*",
    ]

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    return path
